version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - REACT_APP_API_URL=http://localhost:4000
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/social-media-app
      - JWT_SECRET=your-secret-key-here
    volumes:
      - ./Server:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    restart: unless-stopped

